#!/bin/sh

GH_USER='kvendrik'

_get_repo_from_origin() {
  echo "$1" | sed -e "s/.git$//" -e "s/.*github.com[:/]\(.*\)/\1/"
}

_get_repo() {
  local origin repo pr_url
  origin="$(git config --get remote.origin.url)"
  repo="$(_get_repo_from_origin "$origin")"
  if [ "$repo" = "" ]; then
    exit 1
  fi
  echo $repo
}

_build_create_pr_url() {
  local branch
  repo="$(_get_repo)"
  pr_url="https://github.com/$repo/pull/new"
  branch="$(git symbolic-ref --short HEAD)"
  base='master'
  if [ "$1" != "" ]; then
    base="$1"
  fi
  echo "$pr_url/$base...$branch"
}

_open_url() {
  if [ "$(uname -s)" = "Darwin" ]; then
    open "$1" 2> /dev/null
  else
    xdg-open "$1" > /dev/null 2> /dev/null
  fi
}

opr() {
  _open_url "$(_build_create_pr_url "$*")"
}

mpr() {
  _open_url "https://github.com/$(_get_repo)/pulls/$GH_USER"
}

mi() {
  _open_url "https://github.com/$(_get_repo)/issues/created_by/$GH_USER"
}
