#!/bin/bash
# shellcheck source=./index

autoload bashcompinit
bashcompinit

DOTFILES_DIRECTORY=$(dirname "$0")

source "$DOTFILES_DIRECTORY/utilities.bash"
source "$DOTFILES_DIRECTORY/file-system/index.bash"
source "$DOTFILES_DIRECTORY/git/index.bash"
source "$DOTFILES_DIRECTORY/images.bash"
source "$DOTFILES_DIRECTORY/network.bash"
source "$DOTFILES_DIRECTORY/random.bash"
source "$DOTFILES_DIRECTORY/yarn.bash"
