#!/usr/bin/env bash

if [[ -z "$(brew ls --versions shellcheck)" ]]; then
  brew install shellcheck
fi

all_files=$(ls -pa | grep -v / | sed /README.md/d | tr '\n' ' ')

echo "Checking $all_files"

shellcheck $all_files