#!/bin/sh

if [ -z "$(command -v shellcheck)" ]; then
  if ! brew install shellcheck; then
    echo 'ShellCheck not found and failed to install through brew. Check shellcheck.net for instructions on how to install ShellCheck.'
    exit 1
  fi
fi

get_all_files_in_directory() {
  local all_files
  local all_local_files
  all_files=''
  all_local_files=$(echo "$1"* | sed -E 's/([^\s\/]+\/)?README\.md//g')
  for file in $(echo $all_local_files); do
    if [ -d "$file" ]; then
      add_files="$(get_all_files_in_directory "$file/")"
      all_files+="$add_files"
    else
      all_files+="$file "
    fi
  done
  echo "$all_files"
}

all_files_to_lint=$(get_all_files_in_directory ./ | sed 's/\.\/lint//')

echo "Checking $all_files_to_lint"

shellcheck $all_files_to_lint