#!/bin/bash

if [ ! -d "$HOME/dotfiles/home" ]; then
  echo "Place the dotfiles in your home folder."
  exit 1
fi

HOME_FILES="$(ls -a "$HOME/dotfiles/home" | grep -E '\.[a-z]+')"

symlink_homefiles() {
  for file in $HOME_FILES
  do
    if [[ "$file" == "." ]] || [[ "$file" == ".." ]]; then
      continue
    fi

    echo "    symlinking $file to $HOME/$file"

    if [[ "$1" == "-f" ]]; then
      ln -sf "$DIRECTORY/home/$file" "$HOME/$file"
    else
      ln -s "$DIRECTORY/home/$file" "$HOME/$file"
    fi
  done
}

install_oh_my_zsh() {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

install_zsh_autosuggestions() {
  if ! git clone https://github.com/zsh-users/zsh-autosuggestions "$HOME/.zsh/zsh-autosuggestions"; then
    echo 'Git clone failed. Aborting.'
    exit 1
  fi
}

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  if [ -n "$SPIN" ]; then
    echo '1/5. Installing Oh My ZSH'
    install_oh_my_zsh
  else
    printf "%s" "1/5. Install Oh My ZSH? [y/N] "
    read -r do_install_oh_my_zsh

    if [[ "$do_install_oh_my_zsh" == 'y' ]]; then
      install_oh_my_zsh
    fi
  fi
else
  echo '1/5. Installing Oh My ZSH. (already installed)'
fi

if [ -n "$SPIN" ]; then
  echo '2/5. Symlinking the custom Oh My ZSH theme'
  ln -sf "$HOME/dotfiles/zsh_themes/robbyrussell_with_host.zsh-theme" "$HOME/.oh-my-zsh/custom/themes/robbyrussell_with_host.zsh-theme"
else
  printf "%s" "2/5. Would you like to symlink the custom Oh My ZSH theme? [y/N] "
  read -r custom_zsh_theme_install

  if [[ "$custom_zsh_theme_install" == 'y' ]]; then
    ln -sf "$HOME/dotfiles/zsh-themes/robbyrussell_with_host.zsh-theme" "$HOME/.oh-my-zsh/custom/themes/robbyrussell_with_host.zsh-theme"
  fi
fi

if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
  if [ -n "$SPIN" ]; then
    echo '3/5. Installing ZSH Autosuggestions'
    install_zsh_autosuggestions
  else
    printf '%s' '3/5. Install ZSH Autosuggestions? [y/N] '
    read -r do_install_zsh_autosuggestions

    if [[ "$do_install_zsh_autosuggestions" == 'y' ]]; then
      install_zsh_autosuggestions
    fi
  fi
else
  echo '3/5. Installing ZSH Autosuggestions. (already installed)'
fi

if [ -n "$SPIN" ]; then
  echo '4/5. Symlinking home files'
  symlink_homefiles -f
else
  printf "%s\n%s\n%s" "4/5. Would you like to symlink the following files to $HOME?" "$HOME_FILES" "[y/N] "
  read -r do_symlink

  if [[ "$do_symlink" == "y" ]]; then
    symlink_homefiles
  fi
fi

if [ -n "$SPIN" ]; then
  echo "5/5. Adding Spin configuration to $HOME/.rc-config"
  echo """
export GITHUB_USERNAME='kvendrik'
export REPOSITORIES_DIRECTORY='/src/github.com/shopify'
  """ > "$HOME/.rc-config"

  exit 0
fi

printf '%s' "5/5. Manually import the Terminal theme found in $HOME/dotfiles/CustomBasic.terminal into your Terminal preferences. Done? [y/n] "
read -r done_manually_importing_theme

printf '\n%s' "[✓] Done. Check out the README.md for further instructions."
