#!/bin/bash

__symlink_homefiles() {
  local dotfiles do_symlink do_force
  dotfiles="$(ls -a ./bootstrap/home | grep -E '\.[a-z]+')"

  if [[ "$1" != "-f" ]]; then
    printf "%s" "Would you like to symlink the following files to $HOME?\n$dotfiles\n[y/N] \c"
    read -r do_symlink

    if [[ "$do_symlink" != "y" ]]; then
      exit 0
    fi
  fi

  for file in $dotfiles
  do
    if [[ "$file" == "." ]] || [[ "$file" == ".." ]]; then
      continue
    fi

    echo "    symlinking $file to $HOME/$file"

    if [[ "$1" == "-f" ]]; then
      ln -sf "$DIRECTORY/home/$file" "$HOME/$file"
    else
      ln -s "$DIRECTORY/home/$file" "$HOME/$file"
    fi
  done
}

if [ -n "$SPIN" ]; then
  echo 'initializing kvendrik/dotfiles'

  __symlink_homefiles -f

  export GITHUB_USERNAME='kvendrik'
  export REPOSITORIES_DIRECTORY='/src/github.com/shopify'

  # shellcheck disable=SC1091
  source "$HOME/dotfiles/index"

  exit 0
fi

__symlink_homefiles

echo "Done. Check out the README.md for further instructions."
