#!/bin/bash
# shellcheck source=./tests/cherry-picking

directory_path=$(dirname "$0")
source "$directory_path/_utilities.bash";

all_scripts="$(get_all_scripts)"

for script_path in $all_scripts; do
  if echo "$script_path" | grep -q 'foundation'; then
    continue
  fi

  private_methods="$(grep -Eo 'function \_\_[^ (]+' "$script_path" | grep -Eo '[^ ]+$')"

  for method_name in $private_methods; do
    if [ -z "$method_name" ]; then
      continue
    fi

    for script_path_to_check in $all_scripts; do
      if echo "$script_path_to_check" | grep -Eq "(foundation|$(basename "$script_path"))"; then
        continue
      fi
      if grep -q "$method_name" "$script_path_to_check"; then
        echo "
$method_name called in $script_path_to_check. Defined in $script_path.

Private methods should only be used in the script they're defined in or they should be defined within the ./foundation folder.

This is to ensure the dotfiles stay cherry-pickable. A consumer should only have to source ./foundation/index.bash and then be able to
source any other script.
"
        exit 1
      fi
    done
  done
done
