version: 2
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - run:
          name: Install Shellcheck
          command: |
            wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv
            sudo mv shellcheck-stable/shellcheck /usr/bin/shellcheck
            shellcheck --version
            rm -rf shellcheck-stable
      - checkout
      - run:
          name: Linting
          command: ./tests/lint
      - run:
          name: Custom Linting
          command: ./tests/custom-linting
      - run:
          name: Cherry-picking
          command: ./tests/cherry-picking

workflows:
  version: 2
  workflow:
    jobs:
      - test
