version: 2

orbs:
  shellcheck: circleci/shellcheck@1.0.0

jobs:
  lint:
    docker:
      - image: quay.io/cfra/shellcheck-circleci
    steps:
      - checkout
      - run: ls
      - run:
          name: Linting
          command: ./lint

workflows:
  version: 2
  workflow:
    jobs:
      - lint
