version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Linting
          command: ./lint

workflows:
  version: 2
  workflow:
    jobs:
      - lint
